sudo apt-get install pkg-config
sudo apt-get install libboost-python-dev
sudo apt-get install libboost-thread-dev
sudo apt-get install libbluetooth-dev
sudo apt-get install libglib2.0-dev
sudo apt-get install python-dev
sudo pip install gattlib
sudo pip install matplotlib
sudo apt-get install python-tk
sudo pip install pybluez
